### ISSUE TITLE
unable to import osgeo gdal from lambda layer

### ISSUE THREAD

**Issue by satwikthegit** [developmentseed/geolambda#102]
Hello,
working with layer arn:aws:lambda:us-west-2:524387336408:layer:gdal33-al2:1 and having set the env vars for GDAL_DATA and PROJ_LIB I'm unable to import gdal from osgeo. 

curious if I'm missing any configuration here..

**Comment by vincentsarago** [comment]
👋 @satwikthegit maybe because you are using https://github.com/lambgeo/docker-lambda ;-) 

the layer `gdal33-al2` doesn't provide any python libs, please checkout the repo documentation
