### ISSUE TITLE
Add example docker run command

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/geolambda#25]
The Readme describes how to get the docker image, but not how to use docker to create the deployment zip. For those not very familiar with docker this is quite confusing.

The following works, and clearly runs, but the resulting zip is not on the host system. It needs some sort of volume mounted, but the internal path is not clear.
```docker run developmentseed/geolambda:min lambda-package.sh```

**Comment by matthewhanson** [comment]
GeoLambda has been refactored and things work quite a bit differently now.   A 1.1.0b1 has been published with a final version coming soon that I think resolves these issues. Please see the `develop` branch for the latest and create any new issues as needed, thanks!
