### ISSUE TITLE
Packaging script only works with :full

### ISSUE THREAD

**Issue by drewbo** [developmentseed/geolambda#27]
I updated my Dockerfile to use `:min` and then tried packaging with `docker-compose run package` and got the following error:

```bash
cp: cannot stat ‘/usr/local/lib/libdf.so.0’: No such file or directory
cp: cannot stat ‘/usr/local/lib/libsz.so.2’: No such file or directory
cp: cannot stat ‘/usr/local/lib/libhdf5.so.101’: No such file or directory
cp: cannot stat ‘/usr/local/lib/libmfhdf.so.0’: No such file or directory
```

I think those libs aren't installed in this tag so the `cp` fails. Probably should be made conditional but I couldn't think of a quick fix

**Comment by matthewhanson** [comment]
As GeoLambda has been refactored and no longer uses the min tag this issue has been OBE'd
