### ISSUE TITLE
Dockerfile.hdf build doesn't work

### ISSUE THREAD

**Issue by SergioIsBored** [developmentseed/geolambda#30]
when builded with the current configuration, the testpackage  service produce this output:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/geolambda/test/test_lambda.py", line 4, in <module>
    lambda_handler = imp.load_source('lambda_handler', 'lambda/lambda_handler.py')
  File "lambda/lambda_handler.py", line 16, in <module>
    from osgeo import gdal
ImportError: No module named osgeo

----------------------------------------------------------------------
Ran 1 test in 0.024s

**Comment by matthewhanson** [comment]
@SergioIsBored I thought I had fixed this in the last couple weeks. Are you using the latest changes on the master branch?

**Comment by SergioIsBored** [comment]
i am. i've cloned the repo more than one time. Actually i'm trying to build a netcdf4 enabled version on top of that, so at first i thought that was the reason. But i've wiped all clean and restarted fresh. Same issue.

**Comment by SergioIsBored** [comment]
i've also tried uncomment:
       --with-geos=$PREFIX/bin/geos-config \
        --with-proj4=$PREFIX \
in the gdal section of the file, no luck.

**Comment by SergioIsBored** [comment]
if there's anything i can do to help you figure this out, let me know.

**Comment by matthewhanson** [comment]
thanks @SergioIsBored I'm building and testing it, I think I know where the problem lies and should have it updated by tonight.

**Comment by matthewhanson** [comment]
@SergioIsBored I was unable to reproduce your problem.

In the geolambda-seed directory I ran
```
$ docker-compose build
$ docker-compose run package
$ docker-compose run testpackage
```

Have you changed the GDAL version at all? The error you are getting is it can't find the osgeo package. When compiling the GDAL python bindings from scratch they are installed into a egg directory, and that is linked to from easy_install. When geolambda packages things up it instead just links directly into that directory, i.e.,
```
osgeo -> GDAL-2.2.2-py2.7-linux-x86_64.egg/osgeo/
```
But that GDAL version is hardcoded into the package file, so if the environment variable is changed for the GDAL version, this won't work. You'd need to change the file here:
https://github.com/developmentseed/geolambda/blob/master/bin/lambda-package-base.sh#L26

What needs to happen is that should either search for the GDAL directory and create the link to that, or better would not be to have it installed as an egg to begin with.

If this isn't the problem, then I'm not sure....could you give some details as to how you are building and testing?

**Comment by SergioIsBored** [comment]
i will test it again in a clean environment an let you know the results.

**Comment by SergioIsBored** [comment]
could it be that by pulling layers from the docker-compose i'm getting an outdated version?

**Comment by SergioIsBored** [comment]
in the geolambda directory i ran:

docker build -f Dockerfile.netcdf -t developmentseed/geolambda:netcdf .
then in the geolambda-seed, same as yours.

**Comment by SergioIsBored** [comment]
by the way, may i suggest the following change:
name of the python file: from lambda_handler to lambda_function
name of the function in the file: from handler to lambda_handler

This way the file would reflect the preset of the aws environment, resulting in a single upload step.

**Comment by SergioIsBored** [comment]
Now it works.
