### ISSUE TITLE
Library version updates

### ISSUE THREAD

**Issue by matthewhanson** [developmentseed/geolambda#60]
Ongoing issue to track changes to included library versions. When there's sufficient changes we will cut a new release.

**Comment by matthewhanson** [comment]
libopenjpeg 2.3.1 released
http://www.openjpeg.org/2019/04/02/OpenJPEG-2.3.1-released

**Comment by robertd** [comment]
curl 7.64.1 released
https://curl.haxx.se/download.html

**Comment by robertd** [comment]
nghttp2 v1.37.0 released
https://github.com/nghttp2/nghttp2/releases/

**Comment by robertd** [comment]
libgeotiff 1.5.1 released
https://download.osgeo.org/geotiff/libgeotiff/?C=M;O=D

**Comment by robertd** [comment]
netcdf-c 4.6.3 released
https://github.com/Unidata/netcdf-c/releases

**Comment by robertd** [comment]
libwebp 1.0.2 released
https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.0.2

**Comment by robertd** [comment]
jpeg-turbo 2.0.2 released
https://github.com/facebook/zstd/releases

**Comment by matthewhanson** [comment]
All of the above have now been merged into develop thanks to @robertd, except for libgeotiff which stays at 1.4.3 for now.  If we can get 1.5.x working prior to the next release (by end of month?) we can include it.
