### ISSUE TITLE
Possible to use with node ogr2ogr?

### ISSUE THREAD

**Issue by stdmn** [developmentseed/geolambda#66]
Apologies if this is more of a StackOverflow question, but I'm trying to run [ogr2ogr](https://github.com/wavded/ogr2ogr) to push user-uploaded files to a Postgres database. The ogr2ogr module requires a native install of GDAL.

I've added your Lambda layer to my function but not sure if I need to import or call it. Thoughts?

**Comment by matthewhanson** [comment]
Wow, sorry I never responded to this @stdmn .

You can use the layer, but you will need to include the ogr2ogr executable in your own deployment.

**Comment by matthewhanson** [comment]
Also asked in #80 and responded here: https://github.com/developmentseed/geolambda/issues/80#issuecomment-553551347
