### ISSUE TITLE
Release lambda layers into eu-west-2 (London)

### ISSUE THREAD

**Issue by JoelClemence** [developmentseed/geolambda#83]
We are using AWS in EU-West 2 (London) and would like the lambda layer to be available in eu-west-2. We need the version 2.0.0 and 2.0.0-python layers

**Comment by matthewhanson** [comment]
@JoelClemence thanks for the request - yes I will add eu-west-2 to the deployment in the next release.

**Comment by JoelClemence** [comment]
@matthewhanson Thanks, that is great, do you know when that will be roughly speaking?

**Comment by matthewhanson** [comment]
@JoelClemence I've got a couple other things to add to it, shooting for releasing 2.0.1 next week

**Comment by JoelClemence** [comment]
@matthewhanson  that's great. Thanks!

**Comment by axwalker** [comment]
@matthewhanson is there any update on when this might be available? Thanks.
