### ISSUE TITLE
Basic usage failure?

### ISSUE THREAD

**Issue by ramotswa** [developmentseed/geolambda#93]
Hello all,
So I did what I thought would be the simplest test ever.
1. Created python lambda in eu-central-1
2. Added the layer via ARN for the latest for that region
3. Set the env vars.
4. Literally just put an 'from osgeo import gdal' into the default python lambda code. 
5. Tested it.

I get 'Unable to import module ..: No module named osgeo'

Should that work?

Many thanks

**Comment by fpolignano** [comment]
@ramotswa I've also tried setting up a simple test like yours but get the error:  "No module named '_gdal'"
I'm wondering if we are missing a step? I've added 2 layers - 

arn:aws:lambda:us-east-1:552188055668:layer:geolambda:4
arn:aws:lambda:us-east-1:552188055668:layer:geolambda-python:3

@matthewhanson Should @ramotswa workflow work? Or are we missing an important step? I'd like to get confirmation that this workflow should work. If this is a valid workflow, perhaps I've misconfigured my lambda function. 

Thanks for any help - really eager to get this working. 

![image](https://user-images.githubusercontent.com/9319623/94627558-e9bb2d80-028b-11eb-93e3-b84f46335166.png)

![image](https://user-images.githubusercontent.com/9319623/94627584-f63f8600-028b-11eb-83da-c943e82217fa.png)

**Comment by fpolignano** [comment]
@ramotswa What version of Python are you using? I was using 3.6 and switched to 3.7 and it works now. I tried 3.8 and 2.7 out of curiosity and they also didn't work, so I guess this are layers are targeted for 3.7 python runtime.

**Comment by ramotswa** [comment]
Interesting - I'm sure I was using 2.7 so that might explain it. Thanks for
the tests.

**Comment by matthewhanson** [comment]
Has this been resolved?  The Python GeoLambda is Python 3.7.   I tried this out with Python 3.8 and confirmed it fails with that error message.

Working on some updates and will try to generate layers for multiple Python versions.

**Comment by fpolignano** [comment]
Resolved as far as I'm concerned. Looking forward to multiple versions of python supported. Thanks
