### ISSUE TITLE
Update to GDAL > 3.1 for COG driver

### ISSUE THREAD

**Issue by furick1** [developmentseed/geolambda#96]
Need a GDAL update to 3.1 or greater to get Cloud Optimized GeoTIFF generator (https://gdal.org/drivers/raster/cog.html).
I downloaded the repo and updated the dockerfile to what seems like works with updated gdal and other packages as well. Anyone want to give it a try?
[Dockerfile.txt](https://github.com/developmentseed/geolambda/files/5846017/Dockerfile.txt)

**Comment by vincentsarago** [comment]
@furick1 there is a PR #95 open which will update the image to 3.2.1

**Comment by matthewhanson** [comment]
@furick1 thanks, as @vincentsarago referenced, there is an open PR, I was trying to get this built last week but ran into the GDAL issue mentioned there.   And then moved onto something else.

Would be great to get a new version out, I'll check out your Dockerfile.

**Comment by vincentsarago** [comment]
@matthewhanson FYI, I ran into the same issue (with the elastic driver) when adding GDAL 3.2 in https://github.com/lambgeo/docker-lambda/blob/master/dockerfiles/gdal3.2/Dockerfile and decided to remove it as most optional driver https://github.com/lambgeo/docker-lambda/blob/master/dockerfiles/gdal3.2/Dockerfile#L113

The important gotcha I found was for configuring libtiff and libgeotiff for PROJ and GDAL https://github.com/rasterio/rasterio-wheels/issues/65#issuecomment-749639594
